### ISSUE TITLE
Cannot upload anything downloaded to drive automatically

### ISSUE THREAD

**Issue by arjuntsgowda** [reaitten/tgtk#22]
The logs are
2021-05-11T01:06:58.344533+00:00 app[web.1]: 2021-05-11 06:36:58,344 INFO MainThread tk.functions.QBittorrentWrap AttrDict({'added_on': 0, 'amount_left': 0, 'auto_tmm': False, 'availability': 0, 'category': '', 'completed': 0, 'completion_on': -19800, 'content_path': '', 'dl_limit': -1, 'dlspeed': 0, 'downloaded': 0, 'downloaded_session': 0, 'eta': 8640000, 'f_l_piece_prio': False, 'force_start': False, 'hash': 'dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c', 'last_activity': 0, 'magnet_uri': 'magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big%20Buck%20Bunny&tr=udp%3a%2f%2fexplodie.org%3a6969&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2ftracker.empire-js.us%3a1337&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337&tr=wss%3a%2f%2ftracker.btorrent.xyz&tr=wss%3a%2f%2ftracker.fastcast.nz&tr=wss%3a%2f%2ftracker.openwebtorrent.com&ws=https%3a%2f%2fwebtorrent.io%2ftorrents%2f', 'max_ratio': -1, 'max_seeding_time': -1, 'name': 'Big Buck Bunny', 'num_complete': 0, 'num_incomplete': 0, 'num_leechs': 0, 'num_seeds': 0, 'priority': 1, 'progress': 0, 'ratio': 0, 'ratio_limit': -2, 'save_path': '/tk/Downloads/16206952183035953/', 'seeding_time': 0, 'seeding_time_limit': -2, 'seen_complete': -19800, 'seq_dl': False, 'size': 0, 'state': 'checkingResumeData', 'super_seeding': False, 'tags': '', 'time_active': 0, 'total_size': -1, 'tracker': '', 'trackers_count': 8, 'up_limit': -1, 'uploaded': 0, 'uploaded_session': 0, 'upspeed': 0})
2021-05-11T01:07:48.025336+00:00 app[web.1]: 2021-05-11 06:37:48,022 ERROR MainThread telethon.client.updates Unhandled exception on handle_leech_command
2021-05-11T01:07:48.025347+00:00 app[web.1]: Traceback (most recent call last):
2021-05-11T01:07:48.025347+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-05-11T01:07:48.025348+00:00 app[web.1]:     await callback(event)
2021-05-11T01:07:48.025349+00:00 app[web.1]:   File "/tk/tk/core/HandleManager.py", line 261, in handle_leech_command
2021-05-11T01:07:48.025350+00:00 app[web.1]:     await check_link(e,rclone, is_zip, is_ext)
2021-05-11T01:07:48.025350+00:00 app[web.1]:   File "/tk/tk/functions/Leech_Module.py", line 151, in check_link
2021-05-11T01:07:48.025351+00:00 app[web.1]:     res = await rclone_driver(path[0],rmess,omess)
2021-05-11T01:07:48.025352+00:00 app[web.1]: TypeError: rclone_driver() missing 1 required positional argument: 'dl_task'

The file gets downloaded but doesn't get uploaded to drive, hope it's get fixed soon

**Comment by reaitten** [comment]
ah sorry about this I forgot to fix rclone upload 😅 i'll let you know whenever this gets fixed (probably within 24-48 hours). thanks for including a log!

**Comment by hackevil** [comment]
@reaitten hey, have you fixed the upload bug related to rclone?

**Comment by reaitten** [comment]
> 
> 
> @reaitten hey, have you fixed the upload bug related to rclone?

yeah

**Comment by arjuntsgowda** [comment]
2021-05-15T15:49:42.212445+00:00 app[web.1]: 2021-05-15 21:19:42,212 INFO MainThread tgtk.functions.QBittorrentWrap Client connected successfully to the torrent server. :)
2021-05-15T15:49:42.573305+00:00 app[web.1]: 2021-05-15 21:19:42,573 INFO MainThread tgtk.functions.QBittorrentWrap magnet :- True
2021-05-15T15:49:42.574033+00:00 app[web.1]: 2021-05-15 21:19:42,573 INFO MainThread tgtk.functions.QBittorrentWrap Trying to login in qBittorrent using creds localhost 8090 admin adminadmin
2021-05-15T15:49:42.984611+00:00 app[web.1]: 2021-05-15 21:19:42,984 INFO MainThread tgtk.functions.QBittorrentWrap Client connected successfully to the torrent server. :)
2021-05-15T15:49:43.033473+00:00 app[web.1]: 2021-05-15 21:19:43,033 INFO MainThread tgtk.functions.QBittorrentWrap Got torrent info from ext hash.
2021-05-15T15:49:43.034643+00:00 app[web.1]: 2021-05-15 21:19:43,034 INFO MainThread tgtk.functions.QBittorrentWrap AttrDict({'added_on': 0, 'amount_left': 0, 'auto_tmm': False, 'availability': 0, 'category': '', 'completed': 0, 'completion_on': -19800, 'content_path': '', 'dl_limit': -1, 'dlspeed': 0, 'downloaded': 0, 'downloaded_session': 0, 'eta': 8640000, 'f_l_piece_prio': False, 'force_start': False, 'hash': 'dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c', 'last_activity': 0, 'magnet_uri': 'magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big%20Buck%20Bunny&tr=udp%3a%2f%2fexplodie.org%3a6969&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2ftracker.empire-js.us%3a1337&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337&tr=wss%3a%2f%2ftracker.btorrent.xyz&tr=wss%3a%2f%2ftracker.fastcast.nz&tr=wss%3a%2f%2ftracker.openwebtorrent.com&ws=https%3a%2f%2fwebtorrent.io%2ftorrents%2f', 'max_ratio': -1, 'max_seeding_time': -1, 'name': 'Big Buck Bunny', 'num_complete': 0, 'num_incomplete': 0, 'num_leechs': 0, 'num_seeds': 0, 'priority': 1, 'progress': 0, 'ratio': 0, 'ratio_limit': -2, 'save_path': '/tgtk/Downloads/16210937830148847/', 'seeding_time': 0, 'seeding_time_limit': -2, 'seen_complete': -19800, 'seq_dl': False, 'size': 0, 'state': 'checkingResumeData', 'super_seeding': False, 'tags': '', 'time_active': 0, 'total_size': -1, 'tracker': '', 'trackers_count': 8, 'up_limit': -1, 'uploaded': 0, 'uploaded_session': 0, 'upspeed': 0})
2021-05-15T15:50:34.329345+00:00 app[web.1]: 2021-05-15 21:20:34,327 ERROR MainThread tgtk.functions.rclone_upload something went wrong. check logs for more infomation.
2021-05-15T15:50:34.329362+00:00 app[web.1]: Traceback (most recent call last):
2021-05-15T15:50:34.329363+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/tgtk/functions/rclone_upload.py", line 32, in rclone_driver
2021-05-15T15:50:34.329363+00:00 app[web.1]:     return await rclone_upload(path,message,user_msg,drive_name,rem_base,edtime,conf_path, ul_task)
2021-05-15T15:50:34.329363+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/tgtk/functions/rclone_upload.py", line 64, in rclone_upload
2021-05-15T15:50:34.329364+00:00 app[web.1]:     rclone_pr = subprocess.Popen(
2021-05-15T15:50:34.329365+00:00 app[web.1]:   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
2021-05-15T15:50:34.329365+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2021-05-15T15:50:34.329365+00:00 app[web.1]:   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
2021-05-15T15:50:34.329366+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2021-05-15T15:50:34.329367+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'True'
2021-05-15T15:50:34.664331+00:00 app[web.1]: 2021-05-15 21:20:34,664 INFO MainThread tgtk.functions.QBittorrentWrap Trying to login in qBittorrent using creds localhost 8090 admin adminadmin
2021-05-15T15:50:35.416330+00:00 app[web.1]: 2021-05-15 21:20:35,416 INFO MainThread tgtk.functions.QBittorrentWrap Client connected successfully to the torrent server. :)

 Now there is a different problem and the file is not getting uploaded to rclone drive
